In [2]:
%pylab inline
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from itertools import combinations
from numpy import array,array_equal

from sklearn.model_selection import cross_validate as cv
from sklearn.model_selection import cross_val_score
from sklearn import tree
from sklearn import metrics
from sklearn import ensemble
from sklearn import linear_model 
from sklearn import naive_bayes 

Populating the interactive namespace from numpy and matplotlib


In [3]:
train_dataset = pd.read_csv('train.csv', index_col='ID')

In [4]:
y_name = 'TARGET'
feature_names = train_dataset.columns.tolist()
feature_names.remove(y_name)

X = train_dataset[feature_names]
y = train_dataset[y_name]


In [34]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import ShuffleSplit
skf = ShuffleSplit(n_splits=5, random_state=0)
score_metric = 'roc_auc'
scores = {}

def score_model(model):
    return cross_val_score(model, X, y, cv=skf, scoring=score_metric)

# time: 10s
scores['tree'] = score_model(tree.DecisionTreeClassifier()) 

In [15]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100)
random_forest.fit(X, y)

RandomForestClassifier()

In [29]:
scores['tree'] 

array([0.56883878, 0.58520897, 0.56974604, 0.5727658 , 0.58808788])

In [30]:
scores['forest'] = score_model(ensemble.RandomForestClassifier())

In [36]:
scores['ridge'] = score_model(linear_model.RidgeClassifier())

In [31]:
scores['forest'] 

array([0.75184779, 0.75857561, 0.75930444, 0.76504206, 0.75833782])

In [33]:
scores['ridge']

array([0.79246246, 0.79261151, 0.80012406, 0.78852317, 0.79778388])

In [39]:
ridge = linear_model.Ridge(normalize = True)
coefs = []

Reg = linear_model.Ridge()
Reg.fit(X,y)
co_matrix = Reg.coef_[0]